### ISSUE TITLE
log directory in samples/pytorch_conv3L_mnist.py

### ISSUE THREAD

**Issue by arkhodamoradi** [nmi-lab/dcll#2]
log_dir at: https://github.com/nmi-lab/dcll/blob/master/samples/pytorch_conv3L_mnist.py#L216
should be logdir similar to: https://github.com/lanpa/tensorboardX/blob/master/tensorboardX/writer.py#L192

**Comment by jackokaiser** [comment]
Turns out both spelling `log_dir` and `logdir` are supported: https://github.com/lanpa/tensorboardX/blob/master/tensorboardX/writer.py#L238

Although you're right, when starting tensorboard with command line, it spells `logdir`
