### ISSUE TITLE
label shape and dtype

### ISSUE THREAD

**Issue by arkhodamoradi** [nmi-lab/dcll#3]
label is int and this line https://github.com/nmi-lab/dcll/blob/master/dcll/load_mnist_pytorch.py#L33 creates error for "int" has not a shape/dtype.

workaround?: tl = torch.empty(torch.Size([len(dataset)]), dtype = torch.uint8)

**Comment by vankhoa21991** [comment]
I have the same issue, what is the version of torch and torchvision of this repo?

**Comment by vankhoa21991** [comment]
I think if you return to torchvision 0.2.0 it would work.

**Comment by jackokaiser** [comment]
There is a more recent version of this code now available at https://github.com/nmi-lab/decolle-public
