### ISSUE TITLE
burnin and n_iters

### ISSUE THREAD

**Issue by arkhodamoradi** [nmi-lab/dcll#4]
In the sample code for MNIST, why [burnin](https://github.com/nmi-lab/dcll/blob/master/samples/pytorch_conv3L_mnist.py#L200) and [n_iters](https://github.com/nmi-lab/dcll/blob/master/samples/pytorch_conv3L_mnist.py#L187) are not equal?

**Comment by jackokaiser** [comment]
Hi Alireza,

- `burnin` is the number of timesteps for which we initially compute the forward dynamics without updating the weights (which we normally update on every timestep).
- `n_iters` is the number of timesteps in total.

Therefore, we compute `n_iters` times foward() but only `n_iters - burnin` backward(). Relevant code is here: https://github.com/nmi-lab/dcll/blob/master/dcll/pytorch_libdcll.py#L629.
The reason for the burnin period is that it takes some time for the network dynamics to settle when a new sample is presented, it is quite common in the field.

We are also releasing a newer version of the code on a different repo: https://github.com/nmi-lab/decolle-public

Cheers,
Jacques
